FROM nousresearch/hermes-agent:latest AS hermes-agent

FROM ghcr.io/nesquena/hermes-webui:latest

USER root

COPY --from=hermes-agent --chown=hermeswebuitoo:hermeswebuitoo /opt/hermes /opt/hermes

USER hermeswebuitoo
